# Generated by Django 4.1.3 on 2022-11-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beds', models.IntegerField(default=1)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('long', models.DecimalField(decimal_places=6, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('bedrooms', models.IntegerField(default=1)),
                ('bathrooms', models.IntegerField(default=1)),
                ('check_in', models.DateField(auto_now=True)),
                ('check_out', models.DateTimeField(default='00:00:00')),
                ('instant_book', models.BooleanField(default=False)),
            ],
        ),
    ]
