# Generated by Django 4.1.3 on 2022-11-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='address',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='apartments',
            old_name='name',
            new_name='country',
        ),
        migrations.AddField(
            model_name='apartments',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='apartments',
            name='host_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartments',
            name='ratings',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='check_in',
            field=models.TextField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='apartments',
            name='check_out',
            field=models.TextField(default='00:00:00'),
        ),
    ]
