# Generated by Django 4.1.3 on 2022-11-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_rename_address_apartments_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartments',
            old_name='host_name',
            new_name='name',
        ),
    ]
